### PR TITLE
Add missing variable to `bundle-clean`

### PR DESCRIPTION
**Pull request by skarekrow**
See https://github.com/jdugan6240/kak-bundle/issues/16

### CODE REVIEW

**Comment by skarekrow** [comment]
While the cleaner does run, there is additional issues that pop up:
```

**Comment by jdugan6240** [comment]
That would indeed be the correct way to add it, although I'm curious about the additional issues you mentioned. Could you elaborate?

**Comment by skarekrow** [comment]
@jdugan6240 Sorry keyboard hit enter and I didn't hold shift or something lol. I edited the comment above, it seems to try to `eval` it afterwards. Maybe harmless since the plugin is now gone

**Comment by jdugan6240** [comment]
I can't replicate that problem. Can you share what cleaner you're using for tabs.kak?

**Comment by skarekrow** [comment]
Yeah it's what I posted at https://github.com/jdugan6240/kak-bundle/issues/16#issue-2571212762, specifically:
```
bundle-cleaner tabs.kak %{
  rm ~/.cargo/bin/kak-tabs
}
```

**Comment by jdugan6240** [comment]
Ohh, I know what's going on. tabs.kak is trying to call the kak-tabs binary, which no longer exists since bundle-clean deleted it. That's not something kak-bundle can solve.

I'm going to merge this. Thanks for your willingness to dive in!

**Comment by skarekrow** [comment]
Makes total sense! Thanks again for this wonderful plugin!

**Pull request merged**
